### PR TITLE
Fixed issues related to em data

### LINKED ISSUE #366: Fix issue related to em data

### PR DESCRIPTION
**Pull request by staudtMarius**
Resolves #366

### CODE REVIEW

File: src/test/groovy/edu/ie3/simona/api/data/connection/ExtEmDataConnectionTest.groovy [hunk 1]
```diff
@@ -157,36 +139,16 @@ class ExtEmDataConnectionTest extends Specification implements DataServiceTestDa
...
-                extSimAdapter.ref()
-        )
-
-        when:
-        def wasSent = extEmDataConnection.sendCommunicationMessage(0L, [], Optional.of(900L))
-
-        then:
-        !wasSent
-        dataService.expectNoMessage()
-    }
```
Comment (sebastian-peter) [inline src/test/groovy/edu/ie3/simona/api/data/connection/ExtEmDataConnectionTest.groovy]: Same here

File: src/test/groovy/edu/ie3/simona/api/data/connection/ExtEmDataConnectionTest.groovy [hunk 2]
```diff
@@ -195,33 +157,16 @@ class ExtEmDataConnectionTest extends Specification implements DataServiceTestDa
...
-    def "ExtEmDataConnection should send no message, if no em set points are given"() {
-        given:
-        def dataService = testKit.createTestProbe(DataMessageFromExt)
-        def extSimAdapter = testKit.createTestProbe(ScheduleDataServiceMessage)
-        def extEmDataConnection = new ExtEmDataConnection(controlled, EmMode.BASE)
-        extEmDataConnection.setActorRefs(
-                dataService.ref(),
-                extSimAdapter.ref()
-        )
-        def inputDataMap = [:] as Map
```
Comment (sebastian-peter) [inline src/test/groovy/edu/ie3/simona/api/data/connection/ExtEmDataConnectionTest.groovy]: Same here

**Review by sebastian-peter — APPROVED** [review]
